# docker-compose.yml
version: '3'

services:
  mongo:
    container_name: mongo
    expose:
      - "27017"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo123!
    networks:
      - datasource

  dalle:
    expose:
      - "5001"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dalle
    networks:
      - harpsharp
      - datasource
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

networks:
  harpsharp:
    external: true
  datasource:
    external: true
