# docker-compose.yml
version: '3'

services:
  flask:
    build: .
    container_name: flask_api
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
