# docker-compose.yml
version: '3'

services:
  dalle:
    expose:
      - "5001"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_api
    restart: always
    env_file:
      - .env
