name: AI repo CI/CD (Pyhon)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  AI-CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.4]

    steps:

      - name: Python 체크 아웃
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 배포 Dir 생성
        if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
        working-directory: .
        run: |
          mkdir -p deploy-ai
          echo "${{ secrets.ENV }}" | base64 --decode >> ./deploy-ai/env
          ls deploy-ai -a
          cp ./app.py ./deploy-ai
          cp ./appspec.yml ./deploy-ai 
          cp ./docker-compose.yml ./deploy-ai
          cp ./Dockerfile ./deploy-ai
          cp ./openai_api.py ./deploy-ai
          cp ./requirements.txt ./deploy-ai
          cp ./scripts/* ./deploy-ai

      - name: S3 업로드 및 CD 요청
        if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
        working-directory: ./
        run: |
          ls deploy-ai -a
          cd deploy-ai && zip -r deploy-ai *
          aws s3 cp deploy-ai.zip s3://${{ secrets.AWS_BUCKET_NAME }}/deploy-ai.zip

          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODEDEPLOY_APP_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_BUCKET_NAME }},bundleType=zip,key=deploy-ai.zip
